opacity-rule = [
	"90:class_g = 'st-256color' && focused",
	"75:class_g = 'st-256color' && !focused",
	"90:class_g = 'lmms' && focused",
	"75:class_g = 'lmms' && !focused",
	"90:class_g = 'dmenu' && focused",
	"75:class_g = 'dmenu' && !focused",
	"90:class_g = 'Audacium' && focused",
	"75:class_g = 'Audacium' && !focused",
];
