#!/usr/bin/sh
paper=$(ls ~/.wallpapers | shuf | head -n 1)
xwallpaper --stretch ~/.wallpapers/$paper
xrdb load ~/.config/x11/xresources.conf
wal -i ~/.wallpapers/$paper -n -o ~/.config/wal/postrun
mpd
picom &
xbanish &
dunst &
pulseaudio --start
pipewire &
sxhkd &
exec dwm
